config/routes.rb
ChaosRails::Application.routes.draw do

  match '*path' => 'application#options', via: :options

  get 'seasons/show'

  devise_for :users, controllers: { registrations: 'registrations' } do
    post 'users/stripe'       => 'registrations#create_with_stripe', as: :user_stripe_registration

    get  'users/reactivation' => 'registrations#reactivation', as: :user_reactivation
    post 'users/reactivate'   => 'registrations#reactivate',   as: :reactivate_user
    post 'users/reactivate/stripe' => 'registrations#reactivate_with_stripe', as: :reactivate_user_stripe
  end

  resources :shows,       only: [:index, :show]
  resources :workshops,   only: [:index, :show]
  resources :news,        only: [:index, :show]
  resources :venues,      only: [:index, :show]
  resources :seasons,     only: [:show]
  resources :users,       only: [:show] do
    collection do
      get 'current'          => 'users#current'
      get 'check_membership' => 'users#check_membership'
    end
  end

  get 'events/xts/:id' => 'events#find_by_xts_id'
  get 'attachments/:slug(/:style)' => 'attachments#show'

  get 'admin/' => 'admin#index'
  namespace :admin do
    get 'resources/*page' => 'resources#page', as: :resources

    get 'answer/:id/file' => 'answers#get_file', :as => :answer_get_file

    resources :shows do
      resources :feedbacks, except: [:show]

      collection do
        get 'query_xts'
      end

      member do
        put 'add_questionnaire'
        put 'add_maintenance_due'
        put 'add_staffing_due'
        put 'create_sdebts'
        get 'create_mdebts'
        get 'xts_report'
      end
    end

    resources :workshops

    resources :debt_notifications, only: [:index]

    resources :staffing_debts do
      member do
        get 'assign'
        get 'unassign'
      end
    end

    resources :maintenance_debts do
      member do
        put 'convert_to_staffing_debt'
      end
    end

    resources :debts

    resources :show_maintenance_debts
    resources :show_staffing_debts

    resources :venues
    resources :seasons
    resources :news
    resources :fault_reports

    resources :opportunities do
      member do
        put 'approve'
        put 'reject'
      end
    end

    resources :editable_blocks, except: [:show]
    resources :mass_mails

    resources :users do
      member do
        post 'reset_password'
      end

      collection do
        get  'autocomplete_list', constraints: { format: :json }
      end
    end

    resources :membership_cards, only: [:index, :show, :create, :destroy] do
      get 'generate_card'
    end

    resources :roles
    get  '/permissions/grid' => 'permissions#grid', :as => :permissions
    post '/permissions/grid' => 'permissions#update_grid', :as => :update_permissions

    resources :techie_families do
      collection do
        get 'graph'
      end
    end

    resources :staffing_templates
    resources :staffings do
      member do
        get 'show_sign_up'
      end

      collection do
        get 'new_for_show'
        put 'create_for_show'
        get ':show_title/grid' => 'staffings#grid', :format => :html, :as => :grid
        get 'guidelines'
      end
    end

    match '/staffings/job/:id/sign_up_confirm' => 'staffings#sign_up_confirm', :via => [:get, :put], :as => :sign_up_confirm
    put '/staffings/job/:id/sign_up' => 'staffings#sign_up', :as => :staffing_sign_up

    get '/proposals' => redirect('/admin/proposals/calls')
    namespace :proposals do
      resources :calls do
        member do
          put 'archive'
        end

        resources :proposals do
          member do
            put 'approve'
            put 'reject'
            put 'convert'
          end
        end
      end

      get '/about' => 'proposals#about'
      resources :call_question_templates
    end

    namespace :questionnaires do
      resources :questionnaires, except: [:new, :create] do
        member do
          get  'answer' => 'questionnaires#answer'
          post 'answer' => 'questionnaires#set_answers'
        end
      end

      resources :questionnaire_templates
    end

    get '/reports/' => 'reports#index', :as => 'reports'
    get '/reports/:action', controller: 'reports', as: 'report'

    get 'jobs/:action' => 'job_control', :as => 'jobs'

    get '/help/:action' => 'help', :as => 'help'
  end

  get 'archives' => 'archives#index', :as => :archives_index
  namespace :archives do
    get 'shows' => 'shows#index', :as => :shows_index
    get 'workshops' => 'workshops#index', :as => :workshops_index
    get 'proposals' => 'proposals#index', :as => :proposals_index
  end

  post 'markdown/preview' => 'markdown#preview'

  get 'about' => 'about#index', :as => :about_index
  get 'about/*page' => 'about#page', :as => :about

  get 'getinvolved' => 'get_involved#index', :as => :get_involved_index
  get 'getinvolved/opportunities' => 'get_involved#opportunities'
  get 'getinvolved/*page' => 'get_involved#page', :as => :get_involved
  get 'youth', to: redirect('/getinvolved/youth_project')

  get '/404' => 'static#render_404'
  get '/500' => 'static#render_500'

  get '/:id' => 'seasons#show', :constraints => ExistingSeasonConstraint.new
  get '*action' => 'static', :as => :static

  root to: 'static#home'

end

app/models/workshop.rb
# == Schema Information
#
# Table name: events
#
# *id*::                 <tt>integer, not null, primary key</tt>
# *name*::               <tt>string(255)</tt>
# *tagline*::            <tt>string(255)</tt>
# *slug*::               <tt>string(255)</tt>
# *description*::        <tt>text</tt>
# *xts_id*::             <tt>integer</tt>
# *created_at*::         <tt>datetime, not null</tt>
# *updated_at*::         <tt>datetime, not null</tt>
# *is_public*::          <tt>boolean</tt>
# *image_file_name*::    <tt>string(255)</tt>
# *image_content_type*:: <tt>string(255)</tt>
# *image_file_size*::    <tt>integer</tt>
# *image_updated_at*::   <tt>datetime</tt>
# *start_date*::         <tt>date</tt>
# *end_date*::           <tt>date</tt>
# *venue_id*::           <tt>integer</tt>
# *season_id*::          <tt>integer</tt>
# *author*::             <tt>string(255)</tt>
# *type*::               <tt>string(255)</tt>
#--
# == Schema Information End
#++

class Workshop < Event
end

app/controllers/admin/workshops_controller.rb
class Admin::WorkshopsController < AdminController
  load_and_authorize_resource find_by: :slug

  def index
    @title = 'Workshops'
    @workshops = Workshop.paginate(page: params[:page], per_page: 15).all
  end

  def show
    @workshop = Workshop.find_by_slug(params[:id])
    @title = @workshop.name
  end

  def new
    @workshop = Workshop.new
    @users = User.by_first_name.all
    @title = 'New Workshop'
  end

  def create
    @workshop = Workshop.new(params[:workshop])
    @users = User.by_first_name.all

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to admin_workshop_url(@workshop), notice: 'Workshop was successfully created.' }
      else
        format.html { render 'new' }
      end
    end
  end

  def edit
    @workshop = Workshop.find_by_slug(params[:id])
    @users = User.by_first_name.all
    @title = "Editing #{@workshop.name}"
  end

  def update
    @workshop = Workshop.find_by_slug(params[:id])
    @users = User.by_first_name.all

    respond_to do |format|
      if @workshop.update_attributes(params[:workshop])
        format.html { redirect_to admin_workshop_url(@workshop), notice: 'Workshop was successfully updated.' }
      else
        format.html { render 'edit' }
      end
    end
  end

  def destroy
    @workshop = Workshop.find_by_slug(params[:id])
    @workshop.destroy

    respond_to do |format|
      format.html { redirect_to admin_workshops_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/archives/workshops_controller.rb
class Archives::WorkshopsController < ArchivesController
  def index
    @q = Workshop.search(params[:q])
    @workshops = @q.result(distinct: true)
                 .paginate(page: params[:page], per_page: 5)
                 .where(is_public: true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workshops }
    end
  end
end

app/controllers/workshops_controller.rb
##
# Public controller for Workshop. More details can be found there.
#
# Uses Will_Paginate for pagination.
##
class WorkshopsController < ApplicationController
  ##
  # GET /workshops
  #
  # GET /workshops.json
  ##
  def index
    @workshops = Workshop.paginate(page: params[:page], per_page: 5).current.order('start_date ASC')

    @title = 'Workshops'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workshops }
    end
  end

  ##
  # GET /workshops/1
  ##
  def show
    # Use ! on find_by to ensure a ActiveRecord::RecordNotFound exception is thrown if the workshop doesn't exist.
    # This is caught by the application controller to redirect to 404
    @workshop = Workshop.find_by_slug!(params[:id])

    @title = @workshop.name
    @meta[:description] = @workshop.description
    @meta['og:image'] = [@base_url + @workshop.image.url(:medium)] + @workshop.pictures.collect { |p| @base_url + p.image.url }

    respond_to do |format|
      format.html
    end
  end
end

app/views/admin/workshops/_form.html.erb
<%= simple_nested_form_for [:admin, @workshop] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :name, :wrapper => :append do %>
      <%= f.input_field :name %>
    <% end %>

    <%= f.input :tagline %>

    <%= f.input :slug %>

    <%= f.input :author %>

    <%= f.input :start_date %>

    <%= f.input :end_date %>

    <%= f.input :price %>

    <%= render :partial => "admin/shared/md_editor", :locals => { :f => f, :field => :description } %>

    <%= f.association :venue, :collection => Venue.all, :label_method => :name %>

    <%= f.association :season, :collection => Season.all, :label_method => :name %>

    <%= f.input :xts_id, label: "XTS ID", hint: "This is the identifier XTS uses to refer to your workshop." %>

    <%= f.input :image %>

    <div class="control-group">
      <%= f.label :is_public %>

      <div class="controls switch" data-on="success" data-on-label="Published" data-off="danger" data-off-label="Private" style="width: 200px;">
        <%=
           f.input_field :is_public,
                          boolean_style: :inline
        %>
      </div>
    </div>

    <div class="form-horizontal">

      <h3>Team</h3>

      <% if f.object.errors[:team_members].present? then %>
      <p id="team_errors" class="alert alert-error">
          <%= f.error :team_members %>
      </p>
      <% end %>

      <ul class="sortable">
        <%= f.fields_for :team_members, :wrapper => false %>

        <li>
          <%= f.link_to_add :team_members, :class => "btn ui-state-disabled" do %>
            <i class="fa fa-plus"></i> Add Team Member
          <% end %>
        </li>
      </ul>

    </div>

    <div class="gallery-form">

      <h3>Gallery</h3>

      <% if f.object.errors[:pictures].present? then %>
      <p id="picture_errors" class="alert alert-error">
          <%= f.error :pictures %>
      </p>
      <% end %>

      <%= f.simple_fields_for :pictures %>

      <br />

      <% add_photo_text = '<i class="fa fa-plus"></i> Add Photo'.html_safe %>
      <%= f.link_to_add add_photo_text, :pictures, :class => "btn" %>

    </div>

  </div>

  <script>
    $('#workshop_name').keyup(function() {
        var slug = jQuery.trim($('#workshop_name').val()).replace(/\s+/g,'-').replace(/[^a-zA-Z0-9\-]/g,'').toLowerCase().replace(/\-{2,}/g,'-');
        $('#workshop_slug').val(slug);
    });
  </script>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to 'Cancel', admin_workshops_path, :class => "btn" %>
  </div>
<% end %>

app/views/admin/workshops/_picture_fields.erb
<div class="picture control-group fields span4">
    <%= image_tag f.object.image.url(:thumb), :class => "thumbnail" %>

    <br />

    <%= f.input :image %>

    <%= f.input :description, :input_html => { :rows => 3 } %>

    <% remove_text = '<i class="icon-remove"></i> Delete'.html_safe %>
    <%= f.link_to_remove remove_text, :class => "btn btn-danger" %>
</div>

app/views/admin/workshops/_team_member_fields.erb
<li class="team_member control-group fields <%= "error" if (f.error :user or f.error :position) %>">
    <%= f.hidden_field :id %>
    <%= f.hidden_field :display_order,:class => 'display_order_input' %>

    <i class="icon-sort"></i>

    <%= f.error :user %>
    <%= f.error :position %>

    <%= f.input_field :position, :data => { :provide => "typeahead", :source => ['Director', 'Producer', 'Technical Manager', 'Stage Manager', 'Assistant to Mr B. Hussey'] } %>

    <%= f.input_field :user_id, :collection => @users.collect {|u| ["#{u.first_name} #{u.last_name}".presence || u.email, u.id]} %>

    <% remove_text = '<i class="icon-remove"></i> Remove'.html_safe %>
    <%= f.link_to_remove remove_text, :class => "btn btn-danger" %>
</li>

app/views/admin/workshops/edit.html.erb
<% @title = 'Edit Workshop' %>

<h1>Edit <%= @workshop.name %></h1>

<%= render 'form' %>

app/views/admin/workshops/index.html.erb
<% @title = 'Workshops' %>

<h1>Workshops</h1>

<%= display_block("Workshops (Members Face)", true) %>

<br />
<br />

<table class="table">
    <tbody>
        <tr>
            <th>Name</th>
            <th>Slug</th>
            <th></th>
            <th></th>
        </tr>
        <% @workshops.each do |workshop| %>
        <tr>
            <td><%= link_to workshop.name, admin_workshop_path(workshop) %></td>
            <td><%= workshop.slug %></td>

            <td>
            <% if can? :edit, workshop %>
            <%= link_to 'Edit', edit_admin_workshop_path(workshop)%>
            <% end %>
            </td>

            <td>
            <% if can? :delete, workshop %>
            <%= link_to 'Destroy', admin_workshop_path(workshop), method: :delete, data: { "confirm" => "Deleting " + workshop.name,
                                                                                   "detail"  => "Be warned. Things may break if you continue. <br /> Please type the name of the workshop below if you are absolutely sure you want to do this.",
                                                                                   "type-confirm" => workshop.name } %>
            <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= will_paginate(@workshops) %>

<% if can? :create, Workshop %>
  <%= link_to new_admin_workshop_path, :class => "btn" do %>
    <i class="fa fa-plus"></i> Add Workshop
  <% end %>
<% end %>

app/views/admin/workshops/new.html.erb
<% @title = 'New Workshop' %>

<h1>New Workshop</h1>

<%= render 'form' %>

app/views/admin/workshops/show.html.erb
<% @title = 'Workshop Details' %>

<h1><%= @workshop.name %></h1>
<table class="table table-bordered">
    <tbody>
        <tr>
            <th>Tagline</th>
            <td><%= @workshop.tagline %></td>
        </tr>
        <tr>
            <th>URL Slug</th>
            <td><%= @workshop.slug %></td>
        </tr>
        <tr>
            <th>Description</th>
            <td><%= render_markdown @workshop.description %></td>
        </tr>
        <tr>
            <th>Dates</th>
            <td><%= @workshop.date_range %></td>
        </tr>
        <tr>
            <th>Venue</th>
            <td><%= @workshop.venue.name if @workshop.venue %></td>
        </tr>
        <tr>
            <th>Public?</th>
            <td><%= {true => "Yes", false => "No", nil => "No"}[@workshop.is_public] %>
        </tr>
        <tr>
            <th>Image</th>
            <td><%= image_tag @workshop.image.url(:medium) %></td>
        </tr>
        <tr>
            <th>Team</th>
            <td>
                <% @workshop.team_members.each do |team_member| %>
                  <p>
                  <b><%= team_member.position %></b>

                  <% u = team_member.user %>
                  <%= "#{u.first_name} #{u.last_name}".presence || u.email %>
                  </p>
                <% end %>
            </td>
        </tr>
    </tbody>
</table>

<% if can? :edit, @workshop %>
  <% edit_text = '<i class="fa fa-pencil"></i> Edit'.html_safe %>
  <%= link_to edit_text, edit_admin_workshop_path(@workshop), :class => 'btn' %>
<% end %>