config/routes.rb
ChaosRails::Application.routes.draw do

  match '*path' => 'application#options', via: :options

  get 'seasons/show'

  devise_for :users, controllers: { registrations: 'registrations' } do
    post 'users/stripe'       => 'registrations#create_with_stripe', as: :user_stripe_registration

    get  'users/reactivation' => 'registrations#reactivation', as: :user_reactivation
    post 'users/reactivate'   => 'registrations#reactivate',   as: :reactivate_user
    post 'users/reactivate/stripe' => 'registrations#reactivate_with_stripe', as: :reactivate_user_stripe
  end

  resources :shows,       only: [:index, :show]
  resources :workshops,   only: [:index, :show]
  resources :news,        only: [:index, :show]
  resources :venues,      only: [:index, :show]
  resources :seasons,     only: [:show]
  resources :users,       only: [:show] do
    collection do
      get 'current'          => 'users#current'
      get 'check_membership' => 'users#check_membership'
    end
  end

  get 'events/xts/:id' => 'events#find_by_xts_id'
  get 'attachments/:slug(/:style)' => 'attachments#show'

  get 'admin/' => 'admin#index'
  namespace :admin do
    get 'resources/*page' => 'resources#page', as: :resources

    get 'answer/:id/file' => 'answers#get_file', :as => :answer_get_file

    resources :shows do
      resources :feedbacks, except: [:show]

      collection do
        get 'query_xts'
      end

      member do
        put 'add_questionnaire'
        put 'add_maintenance_due'
        put 'add_staffing_due'
        put 'create_sdebts'
        get 'create_mdebts'
        get 'xts_report'
      end
    end

    resources :workshops

    resources :debt_notifications, only: [:index]

    resources :staffing_debts do
      member do
        get 'assign'
        get 'unassign'
      end
    end

    resources :maintenance_debts do
      member do
        put 'convert_to_staffing_debt'
      end
    end

    resources :debts

    resources :show_maintenance_debts
    resources :show_staffing_debts

    resources :venues
    resources :seasons
    resources :news
    resources :fault_reports

    resources :opportunities do
      member do
        put 'approve'
        put 'reject'
      end
    end

    resources :editable_blocks, except: [:show]
    resources :mass_mails

    resources :users do
      member do
        post 'reset_password'
      end

      collection do
        get  'autocomplete_list', constraints: { format: :json }
      end
    end

    resources :membership_cards, only: [:index, :show, :create, :destroy] do
      get 'generate_card'
    end

    resources :roles
    get  '/permissions/grid' => 'permissions#grid', :as => :permissions
    post '/permissions/grid' => 'permissions#update_grid', :as => :update_permissions

    resources :techie_families do
      collection do
        get 'graph'
      end
    end

    resources :staffing_templates
    resources :staffings do
      member do
        get 'show_sign_up'
      end

      collection do
        get 'new_for_show'
        put 'create_for_show'
        get ':show_title/grid' => 'staffings#grid', :format => :html, :as => :grid
        get 'guidelines'
      end
    end

    match '/staffings/job/:id/sign_up_confirm' => 'staffings#sign_up_confirm', :via => [:get, :put], :as => :sign_up_confirm
    put '/staffings/job/:id/sign_up' => 'staffings#sign_up', :as => :staffing_sign_up

    get '/proposals' => redirect('/admin/proposals/calls')
    namespace :proposals do
      resources :calls do
        member do
          put 'archive'
        end

        resources :proposals do
          member do
            put 'approve'
            put 'reject'
            put 'convert'
          end
        end
      end

      get '/about' => 'proposals#about'
      resources :call_question_templates
    end

    namespace :questionnaires do
      resources :questionnaires, except: [:new, :create] do
        member do
          get  'answer' => 'questionnaires#answer'
          post 'answer' => 'questionnaires#set_answers'
        end
      end

      resources :questionnaire_templates
    end

    get '/reports/' => 'reports#index', :as => 'reports'
    get '/reports/:action', controller: 'reports', as: 'report'

    get 'jobs/:action' => 'job_control', :as => 'jobs'

    get '/help/:action' => 'help', :as => 'help'
  end

  get 'archives' => 'archives#index', :as => :archives_index
  namespace :archives do
    get 'shows' => 'shows#index', :as => :shows_index
    get 'workshops' => 'workshops#index', :as => :workshops_index
    get 'proposals' => 'proposals#index', :as => :proposals_index
  end

  post 'markdown/preview' => 'markdown#preview'

  get 'about' => 'about#index', :as => :about_index
  get 'about/*page' => 'about#page', :as => :about

  get 'getinvolved' => 'get_involved#index', :as => :get_involved_index
  get 'getinvolved/opportunities' => 'get_involved#opportunities'
  get 'getinvolved/*page' => 'get_involved#page', :as => :get_involved
  get 'youth', to: redirect('/getinvolved/youth_project')

  get '/404' => 'static#render_404'
  get '/500' => 'static#render_500'

  get '/:id' => 'seasons#show', :constraints => ExistingSeasonConstraint.new
  get '*action' => 'static', :as => :static

  root to: 'static#home'

end

app/models/admin/staffing_template.rb
# == Schema Information
#
# Table name: admin_staffing_templates
#
# *id*::         <tt>integer, not null, primary key</tt>
# *name*::       <tt>string(255)</tt>
# *created_at*:: <tt>datetime, not null</tt>
# *updated_at*:: <tt>datetime, not null</tt>
#--
# == Schema Information End
#++

class Admin::StaffingTemplate < ActiveRecord::Base
  has_many :staffing_jobs, as: :staffable, class_name: 'Admin::StaffingJob', dependent: :destroy

  accepts_nested_attributes_for :staffing_jobs, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true

  attr_accessible :name, :staffing_jobs, :staffing_jobs_attributes
end

app/controllers/admin/staffing_templates_controller.rb
##
# Controller for Admin::StaffingTemplate. More details can be found there.
##
class Admin::StaffingTemplatesController < AdminController
  load_and_authorize_resource class: Admin::StaffingTemplate

  ##
  # GET /admin/staffing_templates
  #
  # GET /admin/staffing_templates.json
  ##
  def index
    @templates = Admin::StaffingTemplate.all
    @title = 'Staffing Templates'
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @templates }
    end
  end

  ##
  # GET /admin/staffing_templates/1
  #
  # GET /admin/staffing_templates/1.json
  ##
  def show
    @template = Admin::StaffingTemplate.find(params[:id])
    @title = 'Staffing Templates'
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @template.to_json(include: { staffing_jobs: {} }) }
    end
  end

  ##
  # GET /admin/staffing_templates/new
  #
  # GET /admin/staffing_templates/new.json
  ##
  def new
    @template = Admin::StaffingTemplate.new
    @title = 'New Staffing Template'
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @template }
    end
  end

  ##
  # GET /admin/staffing_templates/1/edit
  ##
  def edit
    @template = Admin::StaffingTemplate.find(params[:id])
    @title = 'Editing Staffing Template'
  end

  ##
  # POST /admin/staffing_templates
  #
  # POST /admin/staffing_templates.json
  ##
  def create
    @template = Admin::StaffingTemplate.new(params[:admin_staffing_template])

    respond_to do |format|
      if@template.save
        flash[:success] = 'Staffing template was successfully created.'
        format.html { redirect_to admin_staffing_template_path(@template) }
        format.json { render json: @template, status: :created, location: @template }
      else
        format.html { render 'new' }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # PUT /admin/staffing_templates/1
  #
  # PUT /admin/staffing_templates/1.json
  ##
  def update
    @template = Admin::StaffingTemplate.find(params[:id])

    respond_to do |format|
      if@template.update_attributes(params[:admin_staffing_template])
        flash[:success] = 'Staffing template was successfully updated.'
        format.html { redirect_to admin_staffing_template_path(@template) }
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # DELETE /admin/staffing_templates/1
  #
  # DELETE /admin/staffing_templates/1.json
  ##
  def destroy
    @template = Admin::StaffingTemplate.find(params[:id])
    @template.destroy

    respond_to do |format|
      format.html { redirect_to admin_staffing_templates_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/staffing_templates/_form.html.erb
<%= simple_nested_form_for(@template) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :name %>

    <div class="well form-horizontal">
    <h3>Jobs</h3>
    <%= f.simple_fields_for :staffing_jobs %>

    <% add_job_text = '<i class="fa fa-plus"></i> Add Job'.html_safe %>
    <%= f.link_to_add add_job_text, :staffing_jobs, :class => "btn" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to 'Cancel', admin_staffing_templates_path, :class => "btn" %>
  </div>
<% end %>

app/views/admin/staffing_templates/_staffing_job_fields.erb
<div class="job control-group fields">
    <%= f.input_field :name %>

    <% remove_text = '<i class="icon-remove"></i> Remove'.html_safe %>
    <%= f.link_to_remove remove_text, :class => "btn btn-danger" %>
</div>

app/views/admin/staffing_templates/edit.html.erb
<h1>Editing Staffing Template</h1>

<%= render 'form' %>

app/views/admin/staffing_templates/index.html.erb
<h1>Staffing Templates</h1>

<table class="table">
  <tr>
    <th>Name</th>

    <% if can? :edit, Admin::StaffingTemplate %>
    <th></th>
    <% end %>

    <% if can? :delete, Admin::StaffingTemplate %>
    <th></th>
    <% end %>
  </tr>

<% @templates.each do |template| %>
  <tr>
    <td><%= template.name %></td>

    <% if can? :edit, template %>
    <td><%= link_to 'Edit', edit_admin_staffing_template_path(template) %></td>
    <% end %>

    <% if can? :delete, template %>
    <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if can? :create, Admin::StaffingTemplate %>
  <% new_text = '<i class="fa fa-plus"></i> New Template'.html_safe %>
  <%= link_to new_text, new_admin_staffing_template_path, :class => "btn" %>
<% end %>

app/views/admin/staffing_templates/new.html.erb
<h1>New Staffing Template</h1>

<%= render 'form' %>

app/views/admin/staffing_templates/show.html.erb
<h1><%= @template.name %> Staffing Template</h1>

<ul>
  <% @template.staffing_jobs.each do |job| %>
    <li><%= job.name %></li>
  <% end %>
</ul>

<% if can? :edit, @template %>
  <% edit_text = '<i class="fa fa-pencil"></i> Edit'.html_safe %>
  <%= link_to edit_text, edit_admin_staffing_template_path(@template), :class => "btn" %>
<% end %>

<%= link_to 'Back', admin_staffing_templates_path, :class => "btn" %>