config/routes.rb
ChaosRails::Application.routes.draw do

  match '*path' => 'application#options', via: :options

  get 'seasons/show'

  devise_for :users, controllers: { registrations: 'registrations' } do
    post 'users/stripe'       => 'registrations#create_with_stripe', as: :user_stripe_registration

    get  'users/reactivation' => 'registrations#reactivation', as: :user_reactivation
    post 'users/reactivate'   => 'registrations#reactivate',   as: :reactivate_user
    post 'users/reactivate/stripe' => 'registrations#reactivate_with_stripe', as: :reactivate_user_stripe
  end

  resources :shows,       only: [:index, :show]
  resources :workshops,   only: [:index, :show]
  resources :news,        only: [:index, :show]
  resources :venues,      only: [:index, :show]
  resources :seasons,     only: [:show]
  resources :users,       only: [:show] do
    collection do
      get 'current'          => 'users#current'
      get 'check_membership' => 'users#check_membership'
    end
  end

  get 'events/xts/:id' => 'events#find_by_xts_id'
  get 'attachments/:slug(/:style)' => 'attachments#show'

  get 'admin/' => 'admin#index'
  namespace :admin do
    get 'resources/*page' => 'resources#page', as: :resources

    get 'answer/:id/file' => 'answers#get_file', :as => :answer_get_file

    resources :shows do
      resources :feedbacks, except: [:show]

      collection do
        get 'query_xts'
      end

      member do
        put 'add_questionnaire'
        put 'add_maintenance_due'
        put 'add_staffing_due'
        put 'create_sdebts'
        get 'create_mdebts'
        get 'xts_report'
      end
    end

    resources :workshops

    resources :debt_notifications, only: [:index]

    resources :staffing_debts do
      member do
        get 'assign'
        get 'unassign'
      end
    end

    resources :maintenance_debts do
      member do
        put 'convert_to_staffing_debt'
      end
    end

    resources :debts

    resources :show_maintenance_debts
    resources :show_staffing_debts

    resources :venues
    resources :seasons
    resources :news
    resources :fault_reports

    resources :opportunities do
      member do
        put 'approve'
        put 'reject'
      end
    end

    resources :editable_blocks, except: [:show]
    resources :mass_mails

    resources :users do
      member do
        post 'reset_password'
      end

      collection do
        get  'autocomplete_list', constraints: { format: :json }
      end
    end

    resources :membership_cards, only: [:index, :show, :create, :destroy] do
      get 'generate_card'
    end

    resources :roles
    get  '/permissions/grid' => 'permissions#grid', :as => :permissions
    post '/permissions/grid' => 'permissions#update_grid', :as => :update_permissions

    resources :techie_families do
      collection do
        get 'graph'
      end
    end

    resources :staffing_templates
    resources :staffings do
      member do
        get 'show_sign_up'
      end

      collection do
        get 'new_for_show'
        put 'create_for_show'
        get ':show_title/grid' => 'staffings#grid', :format => :html, :as => :grid
        get 'guidelines'
      end
    end

    match '/staffings/job/:id/sign_up_confirm' => 'staffings#sign_up_confirm', :via => [:get, :put], :as => :sign_up_confirm
    put '/staffings/job/:id/sign_up' => 'staffings#sign_up', :as => :staffing_sign_up

    get '/proposals' => redirect('/admin/proposals/calls')
    namespace :proposals do
      resources :calls do
        member do
          put 'archive'
        end

        resources :proposals do
          member do
            put 'approve'
            put 'reject'
            put 'convert'
          end
        end
      end

      get '/about' => 'proposals#about'
      resources :call_question_templates
    end

    namespace :questionnaires do
      resources :questionnaires, except: [:new, :create] do
        member do
          get  'answer' => 'questionnaires#answer'
          post 'answer' => 'questionnaires#set_answers'
        end
      end

      resources :questionnaire_templates
    end

    get '/reports/' => 'reports#index', :as => 'reports'
    get '/reports/:action', controller: 'reports', as: 'report'

    get 'jobs/:action' => 'job_control', :as => 'jobs'

    get '/help/:action' => 'help', :as => 'help'
  end

  get 'archives' => 'archives#index', :as => :archives_index
  namespace :archives do
    get 'shows' => 'shows#index', :as => :shows_index
    get 'workshops' => 'workshops#index', :as => :workshops_index
    get 'proposals' => 'proposals#index', :as => :proposals_index
  end

  post 'markdown/preview' => 'markdown#preview'

  get 'about' => 'about#index', :as => :about_index
  get 'about/*page' => 'about#page', :as => :about

  get 'getinvolved' => 'get_involved#index', :as => :get_involved_index
  get 'getinvolved/opportunities' => 'get_involved#opportunities'
  get 'getinvolved/*page' => 'get_involved#page', :as => :get_involved
  get 'youth', to: redirect('/getinvolved/youth_project')

  get '/404' => 'static#render_404'
  get '/500' => 'static#render_500'

  get '/:id' => 'seasons#show', :constraints => ExistingSeasonConstraint.new
  get '*action' => 'static', :as => :static

  root to: 'static#home'

end

app/models/admin/maintenance_debt.rb
# == Schema Information
#
# Table name: admin_maintenance_debts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  due_by     :date
#  show_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  state      :integer          default(0)
#
class Admin::MaintenanceDebt < ActiveRecord::Base
  belongs_to :user
  belongs_to :show

  attr_accessible :user, :user_id, :due_by, :show, :show_id, :state
  validates :due_by, presence: true
  validates :show_id, presence: true
  validates :user_id, presence: true

  enum state: %i[unfulfilled converted completed]
  # the progress of a maintenance debt is tracked by its state enum
  # with status being used to retrieve if the debt has become overdue and is causing debt

  def self.searchfor(user_fname, user_sname, show_name, show_fulfilled)
    user_ids = User.where('first_name LIKE ? AND last_name LIKE ?', "%#{user_fname}%", "%#{user_sname}%").ids
    show_ids = Show.where('name LIKE ?', "%#{show_name}%")
    maintenance_debts = where(user_id: user_ids, show_id: show_ids)

    maintenance_debts = maintenance_debts.unfulfilled unless show_fulfilled

    return maintenance_debts
  end

  def convert_to_staffing_debt
    staffing_debt = Admin::StaffingDebt.new
    staffing_debt.due_by = due_by
    staffing_debt.show_id = show_id
    staffing_debt.user_id = user_id
    staffing_debt.converted = true
    staffing_debt.save!
    self.state = :converted
    save
  end

  def status(on_date = Date.today)
    case state
    when 'converted' then :converted
    when 'completed' then :completed
    else if due_by < on_date
           :causing_debt
         else
           :unfulfilled
         end
    end
  end
end

app/controllers/admin/maintenance_debts_controller.rb
class Admin::MaintenanceDebtsController < AdminController
  before_action :set_admin_maintenance_debt, only: [:show, :edit, :update, :destroy]

  # GET /admin/maintenance_debts
  def index
    @admin_maintenance_debts = Admin::MaintenanceDebt.all
    @title = 'Maintenance Debts'
    if can? :read, Admin::MaintenanceDebt
      if params[:user_id].present?
        @mdebts = Admin::MaintenanceDebt.where(:user_id => params[:user_id])
      elsif (params.length > 3)
        show_fulfilled = params[:show_fulfilled].present?
        @mdebts = Admin::MaintenanceDebt.searchfor(params[:user_fname], params[:user_sname], params[:show_name],show_fulfilled)
      else
        @mdebts = Admin::MaintenanceDebt.unfulfilled
      end
    else
      @mdebts = @admin_maintenance_debts.where(user_id: current_user.id).unfulfilled
    end

    @mdebts = @mdebts.order(due_by: :asc, show_id: :asc, user_id: :asc).paginate(page: params[:page], per_page: 15)
    @mdebts = @mdebts.all
  end

  # GET /admin/maintenance_debts/1
  def show
    @admin_maintenance_debt = Admin::MaintenanceDebt.find(params[:id])
    authorize!(:read, @admin_maintenance_debt)
  end

  # GET /admin/maintenance_debts/new
  def new
    @admin_maintenance_debt = Admin::MaintenanceDebt.new
    @users = User.all
    @shows = Show.all
  end

  # GET /admin/maintenance_debts/1/edit
  def edit
  end

  def convert_to_staffing_debt
    authorize! :manage, Admin::MaintenanceDebt
    mdebt = Admin::MaintenanceDebt.find(params[:id])
    mdebt.convert_to_staffing_debt()

    respond_to do |format|
      format.html { redirect_to admin_maintenance_debts_url, notice: 'Debt converted to Staffing Debt' }
      format.html { render :no_content }
    end
  end

  # POST /admin/maintenance_debts
  def create
    @admin_maintenance_debt = Admin::MaintenanceDebt.new(admin_maintenance_debt_params)

    if @admin_maintenance_debt.save
      redirect_to @admin_maintenance_debt, notice: 'Maintenance debt was successfully created.'
    else
      redirect_to new_admin_maintenance_debt_url, notice: 'Failed to create new Maintenance Debt contact IT'
    end
  end

  # PATCH/PUT /admin/maintenance_debts/1
  def update
    if @admin_maintenance_debt.update(admin_maintenance_debt_params)
      redirect_to @admin_maintenance_debt, notice: 'Maintenance debt was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/maintenance_debts/1
  def destroy
    @admin_maintenance_debt.state = :completed
    if @admin_maintenance_debt.save
      redirect_to admin_maintenance_debts_url, notice: 'Maintenance debt completed.'
    else
      redirect_to admin_maintenance_debts_url, notice: 'Error marking debt completed'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_admin_maintenance_debt
    @admin_maintenance_debt = Admin::MaintenanceDebt.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def admin_maintenance_debt_params
    params.require(:admin_maintenance_debt).permit(:user_id, :due_by, :show_id)
  end
end

app/helpers/admin/maintenance_debts_helper.rb
module Admin::MaintenanceDebtsHelper
  def staffing_debt_class(staffing_debt)
    case staffing_debt.status
      when :not_signed_up then
        "warning"
      when :awaiting_staffing then
        ""
      when :completed_staffing then
        "success"
      when :causing_debt then
        "error"
      when :forgiven then
        "success"
    end
  end

  def maintenance_debt_class(maintenance_debt)
    case maintenance_debt.status
      when :unfulfilled then
        "warning"
      when :converted then
        "success"
      when :completed then
        "success"
      when :causing_debt then
        "error"
    end
  end
end

app/views/admin/maintenance_debts/_form.html.erb
<%= simple_form_for(@admin_maintenance_debt) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    User: <%= f.input_field :user_id, :collection => @users.collect {|u| ["#{u.first_name} #{u.last_name}".presence || u.email, u.id]} %><br>
    Show: <%= f.input_field :show_id, :collection => @shows.collect {|s| ["#{s.name}" , s.id]} %><br>
    <%= f.input :due_by %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/maintenance_debts/edit.html.erb
<h1>Editing Maintenance Debt</h1>

<%= simple_form_for(@admin_maintenance_debt) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :due_by , label: "Due By"%>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

<%= link_to 'Show', @admin_maintenance_debt %> |
<%= link_to 'Back', admin_maintenance_debts_path %>

app/views/admin/maintenance_debts/index.html.erb
<% @title = 'Maintenance Debts' %>

<% prefix = params.length>3 ? "Searching" : "Listing" %>

<h1><%= prefix %> Maintenance Debts</h1>

<% if can? :read, Admin::MaintenanceDebt %>
        <div class="row">
          <div class="span12">
            <div class="accordion-group">
              <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" href="#search_container">
                  <i class="fa fa-chevron-down"></i> Search Form
                </a>
              </div>
              <div id="search_container" class="accordion-body collapse">
                <div class="accordion-inner">
                  <%= form_tag admin_maintenance_debts_path , :method => :get do %>
                      First Name :<%= text_field_tag :user_fname %>
                      Second Name :<%= text_field_tag :user_sname %>
                      Show : <%= text_field_tag :show_name %>
                      Show Fulfilled Obligations : <%= check_box_tag :show_fulfilled %>

                      <%= submit_tag "Search", class: 'btn' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
<% end %>

<table class="table">
  <tbody>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Show</th>
    <th>Due Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @mdebts.each do |mdebt| %>

      <tr class="<%= maintenance_debt_class(mdebt) %>">
        <td><%= mdebt.user.email %></td>
        <td><%= "#{mdebt.user.first_name} #{mdebt.user.last_name}" %></td>
        <td><%= mdebt.show.name %></td>
        <td><%= mdebt.due_by %></td>

        <td>
          <% if can? :edit, mdebt %>
              <%= link_to 'Change Deadline', edit_admin_maintenance_debt_path(mdebt), class: "btn" %>
          <% end %>
        </td>

        <td>
          <% if (can? :edit, mdebt) && (mdebt.unfulfilled?) %>
              <%= link_to convert_to_staffing_debt_admin_maintenance_debt_path(mdebt.id), :method => :put, class: "btn" do %>
                  Convert To Staffing
              <% end %>
          <% end %>
        </td>

        <td>
          <% if (can? :delete, mdebt) && (mdebt.unfulfilled?) %>
              <%= link_to 'Completed', admin_maintenance_debt_path(mdebt), method: :delete, class: "btn btn-danger", data: {confirm: "Deleting " + mdebt.user.name + "'s debt",
                                                                                                                          detail: "If you delete a debt a theatre manager fairy dies",
              } %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="paginate_holder">
  <%= will_paginate(@mdebts) %>
</div>

<% if can? :create, Admin::MaintenanceDebt %>
    <%= link_to 'Create Maintenance Obligation', new_admin_maintenance_debt_path, class: "btn" %>
<% end %>

<br>

app/views/admin/maintenance_debts/new.html.erb
<h1>New Maintenance Debt</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_maintenance_debts_path %>

app/views/admin/maintenance_debts/show.html.erb
<p>
  <strong>User:</strong>
  <%= @admin_maintenance_debt.user.name %>
</p>

<p>
  <strong>Dueby:</strong>
  <%= @admin_maintenance_debt.due_by %>
</p>

<p>
  <strong>Show:</strong>
  <%= @admin_maintenance_debt.show.name %>
</p>

<%= link_to 'Edit', edit_admin_maintenance_debt_path(@admin_maintenance_debt) %> |
<%= link_to 'Back', admin_maintenance_debts_path %>