config/routes.rb
ChaosRails::Application.routes.draw do

  match '*path' => 'application#options', via: :options

  get 'seasons/show'

  devise_for :users, controllers: { registrations: 'registrations' } do
    post 'users/stripe'       => 'registrations#create_with_stripe', as: :user_stripe_registration

    get  'users/reactivation' => 'registrations#reactivation', as: :user_reactivation
    post 'users/reactivate'   => 'registrations#reactivate',   as: :reactivate_user
    post 'users/reactivate/stripe' => 'registrations#reactivate_with_stripe', as: :reactivate_user_stripe
  end

  resources :shows,       only: [:index, :show]
  resources :workshops,   only: [:index, :show]
  resources :news,        only: [:index, :show]
  resources :venues,      only: [:index, :show]
  resources :seasons,     only: [:show]
  resources :users,       only: [:show] do
    collection do
      get 'current'          => 'users#current'
      get 'check_membership' => 'users#check_membership'
    end
  end

  get 'events/xts/:id' => 'events#find_by_xts_id'
  get 'attachments/:slug(/:style)' => 'attachments#show'

  get 'admin/' => 'admin#index'
  namespace :admin do
    get 'resources/*page' => 'resources#page', as: :resources

    get 'answer/:id/file' => 'answers#get_file', :as => :answer_get_file

    resources :shows do
      resources :feedbacks, except: [:show]

      collection do
        get 'query_xts'
      end

      member do
        put 'add_questionnaire'
        put 'add_maintenance_due'
        put 'add_staffing_due'
        put 'create_sdebts'
        get 'create_mdebts'
        get 'xts_report'
      end
    end

    resources :workshops

    resources :debt_notifications, only: [:index]

    resources :staffing_debts do
      member do
        get 'assign'
        get 'unassign'
      end
    end

    resources :maintenance_debts do
      member do
        put 'convert_to_staffing_debt'
      end
    end

    resources :debts

    resources :show_maintenance_debts
    resources :show_staffing_debts

    resources :venues
    resources :seasons
    resources :news
    resources :fault_reports

    resources :opportunities do
      member do
        put 'approve'
        put 'reject'
      end
    end

    resources :editable_blocks, except: [:show]
    resources :mass_mails

    resources :users do
      member do
        post 'reset_password'
      end

      collection do
        get  'autocomplete_list', constraints: { format: :json }
      end
    end

    resources :membership_cards, only: [:index, :show, :create, :destroy] do
      get 'generate_card'
    end

    resources :roles
    get  '/permissions/grid' => 'permissions#grid', :as => :permissions
    post '/permissions/grid' => 'permissions#update_grid', :as => :update_permissions

    resources :techie_families do
      collection do
        get 'graph'
      end
    end

    resources :staffing_templates
    resources :staffings do
      member do
        get 'show_sign_up'
      end

      collection do
        get 'new_for_show'
        put 'create_for_show'
        get ':show_title/grid' => 'staffings#grid', :format => :html, :as => :grid
        get 'guidelines'
      end
    end

    match '/staffings/job/:id/sign_up_confirm' => 'staffings#sign_up_confirm', :via => [:get, :put], :as => :sign_up_confirm
    put '/staffings/job/:id/sign_up' => 'staffings#sign_up', :as => :staffing_sign_up

    get '/proposals' => redirect('/admin/proposals/calls')
    namespace :proposals do
      resources :calls do
        member do
          put 'archive'
        end

        resources :proposals do
          member do
            put 'approve'
            put 'reject'
            put 'convert'
          end
        end
      end

      get '/about' => 'proposals#about'
      resources :call_question_templates
    end

    namespace :questionnaires do
      resources :questionnaires, except: [:new, :create] do
        member do
          get  'answer' => 'questionnaires#answer'
          post 'answer' => 'questionnaires#set_answers'
        end
      end

      resources :questionnaire_templates
    end

    get '/reports/' => 'reports#index', :as => 'reports'
    get '/reports/:action', controller: 'reports', as: 'report'

    get 'jobs/:action' => 'job_control', :as => 'jobs'

    get '/help/:action' => 'help', :as => 'help'
  end

  get 'archives' => 'archives#index', :as => :archives_index
  namespace :archives do
    get 'shows' => 'shows#index', :as => :shows_index
    get 'workshops' => 'workshops#index', :as => :workshops_index
    get 'proposals' => 'proposals#index', :as => :proposals_index
  end

  post 'markdown/preview' => 'markdown#preview'

  get 'about' => 'about#index', :as => :about_index
  get 'about/*page' => 'about#page', :as => :about

  get 'getinvolved' => 'get_involved#index', :as => :get_involved_index
  get 'getinvolved/opportunities' => 'get_involved#opportunities'
  get 'getinvolved/*page' => 'get_involved#page', :as => :get_involved
  get 'youth', to: redirect('/getinvolved/youth_project')

  get '/404' => 'static#render_404'
  get '/500' => 'static#render_500'

  get '/:id' => 'seasons#show', :constraints => ExistingSeasonConstraint.new
  get '*action' => 'static', :as => :static

  root to: 'static#home'

end

app/models/admin/staffing_debt.rb
# == Schema Information
#
# Table name: admin_staffing_debts
#
#  id                    :integer          not null, primary key
#  user_id               :integer
#  show_id               :integer
#  due_by                :date
#  admin_staffing_job_id :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  converted             :boolean
#  forgiven              :boolean          default(FALSE)
#
class Admin::StaffingDebt < ActiveRecord::Base
  belongs_to :user
  belongs_to :show
  belongs_to :admin_staffing_job, class_name: 'Admin::StaffingJob'

  attr_accessible :due_by, :user, :user_id, :show, :show_id, :admin_staffing_job, :admin_staffing_job_id

  validates :due_by, presence: true
  validates :show_id, presence: true
  validates :user_id, presence: true
  # the status of a staffing debt is determined by whether or not it has a staffing job and if that job is in the past

  def status(on_date = Date.today)
    # note that :awaiting_staffing indicates the staffing slot has not been completed yet AND the debt deadline hasn't passed
    return :forgiven if forgiven
    if !admin_staffing_job.present?
      return :not_signed_up unless due_by < on_date
      :causing_debt
    elsif admin_staffing_job.completed?
      :completed_staffing
    elsif due_by < on_date
      :causing_debt
    else
      :awaiting_staffing
    end
  end

  # returns if the staffing debt has been completed or not
  def fulfilled
    if admin_staffing_job.present?
      admin_staffing_job.completed?
    else
      forgiven
    end
  end

  def self.search_for(user_fname, user_sname, show_name, show_fulfilled)
    user_ids = User.where('first_name LIKE ? AND last_name LIKE ?', "%#{user_fname}%", "%#{user_sname}%").ids
    show_ids = Show.where('name LIKE ?', "%#{show_name}%")
    staffing_debts = where(user_id: user_ids, show_id: show_ids)

    staffing_debts = staffing_debts.unfulfilled unless show_fulfilled

    return staffing_debts
  end

  # returns uncompleted staffing debts
  def self.unfulfilled
    fulfilled_ids = all.map { |debt| debt.fulfilled ? debt.id : nil }
    return where.not(id: fulfilled_ids)
  end

  def forgive
    self.forgiven = true
    save
  end
end

app/controllers/admin/staffing_debts_controller.rb
class Admin::StaffingDebtsController < AdminController
  before_action :set_admin_staffing_debt, only: [:show, :edit, :update, :destroy]

  # GET /admin/staffing_debts
  def index
    @title = 'Staffing Debts'

    if can? :read, Admin::StaffingDebt
      if params[:user_id].present?
        @sdebts = Admin::StaffingDebt.where(:user_id => params[:user_id])
      elsif params.length > 3
        show_fulfilled = params[:show_fulfilled].present?
        @sdebts = Admin::StaffingDebt.search_for(params[:user_fname],params[:user_sname],params[:show_name],show_fulfilled)
      else
        @sdebts = Admin::StaffingDebt.all.unfulfilled
      end
    else
      @sdebts = Admin::StaffingDebt.where(user_id: current_user.id).unfulfilled
    end

    @sdebts = @sdebts.order(due_by: :asc, show_id: :asc, user_id: :asc).paginate(page: params[:page], per_page: 15)
    @sdebts = @sdebts.all
  end

  # GET /admin/staffing_debts/1
  def show
    authorize!(:manage , @admin_staffing_debt)

    boundryDate = Date.today - 80
    @admin_staffing_debt = Admin::StaffingDebt.find(params[:id])
    dateIds = @admin_staffing_debt.user.staffings.where('start_time >?', boundryDate.to_datetime).ids
    @jobs = @admin_staffing_debt.user.staffing_jobs.where(staffable_id: dateIds).where.not(id: Admin::StaffingDebt.pluck(:admin_staffing_job_id), name: 'Committee Rep')
  end


  # GET /admin/staffing_debts/new
  def new
    @admin_staffing_debt = Admin::StaffingDebt.new
    @users = User.all
    @shows = Show.all
  end

  # GET /admin/staffing_debts/1/edit
  def edit
  end

  #associates a debt with a staffing job
  def assign
    authorize! :manage , Admin::StaffingDebt
    debt = Admin::StaffingDebt.find(params[:id])
    debt.update(admin_staffing_job_id: params[:jobid])
    debt.save!

    respond_to do |format|
      format.html { redirect_to admin_staffing_debts_url, notice: 'Job Assigned' }
      format.html { render :no_content }
    end
  end

  def unassign
    authorize! :manage , Admin::StaffingDebt
    debt = Admin::StaffingDebt.find(params[:id])
    debt.update(admin_staffing_job_id: nil)
    debt.save!

    respond_to do |format|
      format.html { redirect_to admin_staffing_debts_url, notice: 'Job Removed' }
      format.html { render :no_content }
    end
  end

  # POST /admin/staffing_debts
  def create
    @admin_staffing_debt = Admin::StaffingDebt.new(admin_staffing_debt_params)

    if @admin_staffing_debt.save
      redirect_to admin_staffing_debts_url, notice: 'Staffing debt was successfully created.'
    else
      redirect_to new_admin_staffing_debt_path, notice: 'Failed to create new staffing Debt, contact IT'
    end
  end

  # PATCH/PUT /admin/staffing_debts/1
  def update
    if @admin_staffing_debt.update(admin_staffing_debt_params)
      redirect_to admin_staffing_debts_url, notice: 'Staffing debt was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/staffing_debts/1
  def destroy
    @admin_staffing_debt.forgive
    redirect_to admin_staffing_debts_url, notice: 'Staffing debt was successfully forgiven.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_staffing_debt
      @admin_staffing_debt = Admin::StaffingDebt.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_staffing_debt_params
      params.require(:admin_staffing_debt).permit(:user_id, :show_id, :due_by, :admin_staffing_job_id)
    end
end

app/helpers/admin/staffing_debts_helper.rb
module Admin::StaffingDebtsHelper
end

app/views/admin/staffing_debts/_form.html.erb
<%= simple_form_for(@admin_staffing_debt) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    User: <%= f.input_field :user_id, :collection => @users.collect {|u| ["#{u.first_name} #{u.last_name}".presence || u.email, u.id]} %><br>
    Show: <%= f.input_field :show_id, :collection => @shows.collect {|s| ["#{s.name}" , s.id]} %><br>
    <%= f.input :due_by %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/staffing_debts/edit.html.erb
<h1>Editing Admin Staffing Debt</h1>

<%= simple_form_for(@admin_staffing_debt) do |y| %>
    <%= y.error_notification %>

    <div class="form-inputs">
      <%= y.input :due_by , label: "Due By"%>
    </div>

    <div class="form-actions">
      <%= y.button :submit %>
    </div>
<% end %>

<%= link_to 'Show', @admin_staffing_debt %> |
<%= link_to 'Back', admin_staffing_debts_path %>

app/views/admin/staffing_debts/index.html.erb
<p id="notice"><%= notice %></p>

<% @title = 'Staffing Debts' %>

<% prefix = params.length > 3 ? "Searching" : "Listing" %>

<h1><%= prefix %> Staffing Debts</h1>

<% if can? :read, Admin::StaffingDebt %>
    <div class="row">
      <div class="span12">
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" href="#search_container">
              <i class="fa fa-chevron-down"></i> Search Form
            </a>
          </div>
          <div id="search_container" class="accordion-body collapse">
            <div class="accordion-inner">
              <%= form_tag admin_staffing_debts_path, :method => :get do %>
                  First Name :<%= text_field_tag :user_fname %>
                  Second Name :<%= text_field_tag :user_sname %>
                  Show : <%= text_field_tag :show_name %> <br/>
                  Show Fulfilled Obligations : <%= check_box_tag :show_fulfilled %>

                  <%= submit_tag "Search", class: 'btn' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

<table class="table">
  <tbody>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Show</th>
    <th>Due Date</th>
    <th>Converted</th>
    <th>Staffing Job</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @sdebts.each do |sdebt| %>

      <tr class="<%= staffing_debt_class(sdebt) %>">
        <td><%= sdebt.user.email %></td>
        <td><%= "#{sdebt.user.first_name} #{sdebt.user.last_name}" %></td>
        <td><%= sdebt.show.name %></td>
        <td><%= sdebt.due_by %></td>
        <td><%= sdebt.converted ? "&#10004;".html_safe : "&#10008;".html_safe%></td>
        <td>
          <% if sdebt.admin_staffing_job.present? %>
              <% job = sdebt.admin_staffing_job.staffable %>
              <%= link_to job.show_title, admin_staffing_path(job) %>
          <% else %>
              <% if can? :edit, sdebt %>
                  <%= link_to 'Associate', admin_staffing_debt_path(sdebt), class: "btn" %>
              <% end %>
          <% end %>
        </td>

        <td>
          <% if (can? :edit, sdebt) && sdebt.admin_staffing_job_id.present? %>
              <%= link_to 'Dissociate', unassign_admin_staffing_debt_path(sdebt), class: "btn" %>
          <% end %>
        </td>

        <td>
          <% if can? :edit, sdebt %>
              <%= link_to 'Change Deadline', edit_admin_staffing_debt_path(sdebt), class: "btn" %>
          <% end %>
        </td>

        <td>
          <% if can? :delete, sdebt %>
              <%= link_to 'Forgive', admin_staffing_debt_path(sdebt), method: :delete, class: "btn btn-danger", data: {confirm: "Deleting " + sdebt.user.name + "'s debt",
                                                                                                                       detail: "If you delete a debt a FOH fairy dies",
              } %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="paginate_holder">
  <%= will_paginate(@sdebts) %>
</div>

<% if can? :create, Admin::StaffingDebt %>
    <%= link_to 'Create Staffing Obligation', new_admin_staffing_debt_path, class: "btn" %>
<% end %>

<br>

app/views/admin/staffing_debts/new.html.erb
<h1>New Admin Staffing Debt</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_staffing_debts_path %>

app/views/admin/staffing_debts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @admin_staffing_debt.user.name_or_email %>
</p>

<p>
  <strong>Show:</strong>
  <%= @admin_staffing_debt.show.name %>
</p>

<p>
  <strong>Dueby:</strong>
  <%= @admin_staffing_debt.due_by %>
</p>

<p>
  <strong>Admin staffing job:</strong>
  <%= @admin_staffing_debt.admin_staffing_job_id %>
</p>

<table class="table">
  <tbody>
  <tr>
    <th>Job</th>
    <th>Date</th>
    <th></th>
  </tr>
  <% @jobs.each do |job| %>

      <tr>
        <td><%= job.staffable.show_title %></td>
        <td><%= job.staffable.start_time.to_s(:long_ordinal)%></td>
        <td>
          <% if true %>
              <%= link_to 'associate' , assign_admin_staffing_debt_path(id:@admin_staffing_debt.id,jobid:job)%>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_admin_staffing_debt_path(@admin_staffing_debt) %> |
<%= link_to 'Back', admin_staffing_debts_path %>